
/**
 * @enum {string} StageStatus
 * Represents the status of a stage in the conversation.
 */
export enum StageStatus {
  LOCKED = 'locked',
  ACTIVE = 'active',
  COMPLETED = 'completed',
}

/**
 * @interface StageDocument
 * Represents a document associated with a stage, used for Retrieval-Augmented Generation (RAG).
 * @property {string} id - The unique identifier for the document.
 * @property {string} name - The name of the document.
 * @property {string} content - The content of the document.
 * @property {string} type - The MIME type of the document.
 */
export interface StageDocument {
  id: string;
  name: string;
  content: string;
  type: string;
}

/**
 * @interface Stage
 * Represents a stage in the conversation.
 * @property {number} id - The unique identifier for the stage.
 * @property {string} title - The title of the stage.
 * @property {string} description - A description of the stage.
 * @property {string} [systemPrompt] - Specific instructions for the AI for this stage.
 * @property {string} [knowledgeBase] - Contextual facts for this stage.
 * @property {StageDocument[]} [documents] - RAG documents for this stage.
 */
export interface Stage {
  id: number;
  title: string;
  description: string;
  systemPrompt?: string; // Specific instructions for this stage
  knowledgeBase?: string; // Context/Facts for this stage
  documents?: StageDocument[]; // RAG Documents
}

/**
 * @interface UserProfile
 * Represents a user's profile.
 * @property {string} [id] - The database ID of the user.
 * @property {string} name - The name of the user.
 * @property {string} phone - The phone number of the user.
 * @property {'PENDING' | 'COMPLETED'} [kycStatus] - The KYC status of the user.
 */
export interface UserProfile {
  id?: string; // Database ID
  name: string;
  phone: string;
  kycStatus?: 'PENDING' | 'COMPLETED';
}

/**
 * @interface TranscriptItem
 * Represents a single item in the conversation transcript.
 * @property {string} id - The unique identifier for the transcript item.
 * @property {'user' | 'agent'} sender - The sender of the message.
 * @property {string} text - The text of the message.
 * @property {Date | string} timestamp - The timestamp of the message.
 */
export interface TranscriptItem {
  id: string;
  sender: 'user' | 'agent';
  text: string;
  timestamp: Date | string; // Allow string for serialized API responses
}

/**
 * @interface CallLog
 * Represents a log of a call session.
 * @property {string} id - The unique identifier for the call log.
 * @property {string} studentName - The name of the student.
 * @property {string} phoneNumber - The phone number of the student.
 * @property {string} date - The date of the call.
 * @property {string} duration - The duration of the call.
 * @property {'Completed' | 'Dropped' | 'Payment Selected'} status - The status of the call.
 * @property {number} stageReached - The final stage reached in the call.
 * @property {string} aiSummary - A summary of the call generated by AI.
 * @property {TranscriptItem[]} transcript - The transcript of the call.
 * @property {string} [paymentMethod] - The payment method selected by the user.
 * @property {string[]} [tags] - Tags for filtering the call log.
 */
export interface CallLog {
  id: string;
  studentName: string;
  phoneNumber: string; 
  date: string; // ISO Date String
  duration: string; // Formatted string or seconds in DB
  status: 'Completed' | 'Dropped' | 'Payment Selected';
  stageReached: number;
  aiSummary: string; 
  transcript: TranscriptItem[]; 
  paymentMethod?: string; // Nullable
  tags?: string[]; // For filtering
}

/**
 * @interface AnalyticsData
 * Represents the analytics data for the application.
 * @property {number} totalCalls - The total number of calls.
 * @property {string} avgDuration - The average duration of calls.
 * @property {number} conversionRate - The conversion rate of calls.
 * @property {number[]} dropOffByStage - The number of drop-offs at each stage.
 * @property {number} [activeNow] - The number of active calls.
 */
export interface AnalyticsData {
  totalCalls: number;
  avgDuration: string;
  conversionRate: number; // Percentage reaching payment
  dropOffByStage: number[]; // [Stage1, Stage2, ...]
  activeNow?: number; // Real-time metric
}

/**
 * @interface SystemConfig
 * Represents the system configuration.
 * @property {string} systemPrompt - The main system prompt for the AI.
 * @property {Stage[]} stages - The stages of the conversation.
 */
export interface SystemConfig {
  systemPrompt: string;
  stages: Stage[];
}

/**
 * @interface LiveServerMessage
 * Represents a message from the Live Server.
 */
export interface LiveServerMessage {
  serverContent?: {
    modelTurn?: {
      parts: {
        inlineData?: {
          mimeType: string;
          data: string;
        };
        text?: string;
      }[];
    };
    turnComplete?: boolean;
    interrupted?: boolean;
    outputTranscription?: {
      text: string;
    };
    inputTranscription?: {
      text: string;
    };
  };
  toolCall?: {
    functionCalls: {
      name: string;
      id: string;
      args: any;
    }[];
  };
}
